"""add assigned_technician_id to tickets

Revision ID: e7a4c39c3ad4
Revises: 64b22c1bb9aa
Create Date: 2026-04-26 10:41:31.370933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7a4c39c3ad4'
down_revision: Union[str, Sequence[str], None] = '64b22c1bb9aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assigned_technician_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tickets_assigned_technician_id'), 'tickets', ['assigned_technician_id'], unique=False)
    op.create_foreign_key(None, 'tickets', 'technicians', ['assigned_technician_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_index(op.f('ix_tickets_assigned_technician_id'), table_name='tickets')
    op.drop_column('tickets', 'assigned_technician_id')
    # ### end Alembic commands ###
